#!/usr/bin/env bash
# script containing commands to automatically configure a Ubuntu machine
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
             listen 80 default_server;
	     listen [::]:80 default_server;
	     root   /var/www/html;
	     index  index.html index.htm;
	      
	     location /redirect_me {
	              return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
             }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
