#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
echo "server {
        listen 80 default_server;
	listen [::]:80 default_server;
	root   /var/www/html;
	index  index.html index.htm;
	location /redirect_me {
	         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
        error_page 404 /custom_404.html;
	location /not-found {
	        root /var/www/html;
		internal;
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
