#!/user/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# username
# user id
# Home directory path for the user

while read -r password
do
	echo "$password" | cut -d ":" -f 1,3,6
done < /etc/passwd
