#!/user/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# username
# user id
# Home directory path for the user

FILE="/etc/passwd"

while read LINE
do
    echo "$LINE" | cut -d ":" -f1,3,6
done < "$FILE"
