#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

HOUR=0; MIN=1

while ((HOUR <= 12))
do
	echo "Hour: $HOUR"

	while ((MIN <= 59))
	do
		echo $MIN
		MIN=$((MIN+1))
	done

	MIN=1
	HOUR=$((HOUR+1))
done
